# Maritime Logistics Agent Configuration
agent:
  name: "MaritimeLogisticsAgent"
  type: "LlmAgent"
  model: "gemini-fast"
  enabled: true
  
# Agent Skills
skills:
  - id: "plan_maritime_transport"
    name: "Plan Maritime Transport"
    description: "Planifica transporte marítimo desde puerto origen hasta destino"
    input_schema:
      type: "object"
      properties:
        origin_port:
          type: "string"
          description: "Puerto de origen"
        destination_port:
          type: "string"
          description: "Puerto de destino"
        cargo_weight:
          type: "number"
          description: "Peso de la carga en toneladas"
        cargo_type:
          type: "string"
          description: "Tipo de carga"
    output_schema:
      type: "object"
      properties:
        vessel_selected:
          type: "string"
        estimated_cost:
          type: "number"
        estimated_time:
          type: "string"
        lay_time:
          type: "string"
        
  - id: "vessel_selection"
    name: "Vessel Selection"
    description: "Selecciona embarcación óptima para la carga"
    input_schema:
      type: "object"
      properties:
        cargo_weight:
          type: "number"
        cargo_type:
          type: "string"
        route:
          type: "string"
    output_schema:
      type: "object"
      properties:
        vessel_name:
          type: "string"
        capacity:
          type: "number"
        availability:
          type: "string"

# Tools Configuration
tools:
  - name: "vessel_selector_tool"
    type: "FunctionTool"
    description: "Selección de embarcaciones disponibles"
    
  - name: "port_coordinator_tool"
    type: "FunctionTool"
    description: "Coordinación con puertos"
    
  - name: "freight_calculator_tool"
    type: "FunctionTool"
    description: "Cálculo de fletes marítimos"

# Argos-specific maritime configuration
argos_specific:
  maritime_partner: "Socio marítimo externo"
  vessels:
    - name: "MV Argos Carrier"
      capacity: 8000
      route: "Cartagena - Mobile, Alabama"
      frequency: "weekly"
    - name: "MV Cement Express"
      capacity: 12000
      route: "Cartagena - Houston, Texas"
      frequency: "bi-weekly"
  ports:
    - name: "Puerto Cartagena"
      country: "Colombia"
      capacity: 15000
    - name: "Mobile, Alabama"
      country: "USA"
      capacity: 20000
